export const styles = {
  root: {
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    maxWidth: 430,
    margin: "0 auto",
    minHeight: "100dvh",
    background: "#080810",
    color: "#111",
    position: "relative",
    overflow: "hidden",
  },
  screen: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100dvh",
    background: "#0d0d18",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "56px 24px 20px",
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: 800,
    color: "#f0f0ff",
    letterSpacing: "-0.8px",
  },
  headerSub: { fontSize: 13, color: "#5a5a7a", marginTop: 3 },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: "8px 18px 120px",
    overflowY: "auto",
  },
  emptyState: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: 40,
    textAlign: "center",
  },
  emptyTitle: { fontSize: 17, fontWeight: 700, color: "#7070a0" },
  emptySub: { fontSize: 13, color: "#4a4a6a" },
  topBar: {
    display: "flex",
    alignItems: "center",
    padding: "52px 20px 20px",
    gap: 12,
    borderBottom: "1px solid rgba(255,255,255,0.04)",
  },
  backBtn: {
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 12,
    padding: "8px 14px",
    fontSize: 14,
    color: "#9090c0",
    cursor: "pointer",
    fontWeight: 600,
    fontFamily: "'Plus Jakarta Sans', sans-serif",
  },
  topTitle: { fontSize: 17, fontWeight: 700, color: "#f0f0ff" },
  formWrap: {
    display: "flex",
    flexDirection: "column",
    padding: "20px 22px 40px",
    gap: 10,
  },
  label: {
    fontSize: 11,
    fontWeight: 700,
    color: "#5a5a7a",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginTop: 8,
  },
  input: {
    borderRadius: 14,
    border: "1.5px solid rgba(255,255,255,0.08)",
    padding: "15px 18px",
    fontSize: 16,
    color: "#f0f0ff",
    background: "rgba(255,255,255,0.05)",
    width: "100%",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    caretColor: "#7c6fff",
  },
  textarea: {
    borderRadius: 14,
    border: "1.5px solid rgba(255,255,255,0.08)",
    padding: "15px 18px",
    fontSize: 15,
    color: "#f0f0ff",
    background: "rgba(255,255,255,0.05)",
    width: "100%",
    resize: "none",
    lineHeight: 1.6,
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    caretColor: "#7c6fff",
  },
  colorGrid: { display: "flex", gap: 10, flexWrap: "wrap", marginTop: 6 },
  colorDot: {
    width: 40,
    height: 40,
    borderRadius: 12,
    cursor: "pointer",
    transition: "transform .2s, box-shadow .2s",
    border: "none",
    flexShrink: 0,
  },
  primaryBtn: {
    borderRadius: 16,
    border: "none",
    padding: "17px 24px",
    fontSize: 15,
    fontWeight: 700,
    color: "#fff",
    width: "100%",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    letterSpacing: "-0.2px",
    cursor: "pointer",
  },
  materiaHeader: {
    display: "flex",
    alignItems: "center",
    padding: "52px 20px 20px",
    justifyContent: "space-between",
  },
  backBtnLight: {
    background: "rgba(0,0,0,0.25)",
    backdropFilter: "blur(8px)",
    border: "1px solid rgba(255,255,255,0.15)",
    borderRadius: 12,
    width: 38,
    height: 38,
    fontSize: 19,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  headerTitleLight: {
    fontSize: 18,
    fontWeight: 800,
    color: "#fff",
    flex: 1,
    textAlign: "center",
    letterSpacing: "-0.4px",
  },
  deleteBtnHeader: {
    background: "rgba(0,0,0,0.25)",
    backdropFilter: "blur(8px)",
    border: "1px solid rgba(255,255,255,0.15)",
    color: "#fff",
    borderRadius: 12,
    width: 38,
    height: 38,
    fontSize: 15,
    cursor: "pointer",
  },
  statsBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 22px",
    borderBottom: "1px solid rgba(255,255,255,0.04)",
  },
  stat: { display: "flex", flexDirection: "column" },
  statNum: { fontSize: 28, fontWeight: 800, lineHeight: 1 },
  statLabel: { fontSize: 11, color: "#5a5a7a", marginTop: 2, fontWeight: 600, letterSpacing: 0.5 },
  materiaCard: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 18,
    padding: "18px",
    cursor: "pointer",
    border: "1px solid rgba(255,255,255,0.06)",
    transition: "transform .15s, box-shadow .15s",
    background: "rgba(255,255,255,0.03)",
    backdropFilter: "blur(10px)",
  },
  bolillaCardBase: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 16,
    background: "rgba(255,255,255,0.04)",
    padding: "18px 16px",
    cursor: "pointer",
    border: "1px solid rgba(255,255,255,0.07)",
  },
  dot: {
    width: 40,
    height: 40,
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  itemName: { fontSize: 15, fontWeight: 700, color: "#e8e8ff" },
  itemSub: { fontSize: 12, color: "#5a5a7a", marginTop: 3 },
  arrow: { fontSize: 20, color: "#3a3a5a", fontWeight: 300 },
  pill: {
    background: "rgba(255,255,255,0.08)",
    color: "#8080b0",
    fontSize: 11,
    fontWeight: 700,
    padding: "4px 10px",
    borderRadius: 8,
    letterSpacing: 0.5,
  },
  studyBtn: {
    borderRadius: 12,
    border: "none",
    padding: "10px 14px",
    fontSize: 12,
    fontWeight: 700,
    color: "#fff",
    cursor: "pointer",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    letterSpacing: 0.3,
  },
  cardItemBody: {
    display: "flex",
    alignItems: "flex-start",
    background: "rgba(255,255,255,0.04)",
    borderRadius: 16,
    padding: "16px",
    gap: 12,
    border: "1px solid rgba(255,255,255,0.06)",
    overflow: "hidden",
    transition: "border-color .2s",
  },
  cardFrontText: {
    fontSize: 14,
    fontWeight: 600,
    color: "#d0d0f0",
    marginBottom: 8,
    wordBreak: "break-word",
    lineHeight: 1.5,
  },
  cardBackText: {
    fontSize: 13,
    color: "#6060a0",
    wordBreak: "break-word",
    lineHeight: 1.5,
  },
  deleteCardBtn: {
    background: "rgba(255,80,80,0.12)",
    border: "1px solid rgba(255,80,80,0.2)",
    borderRadius: 10,
    width: 30,
    height: 30,
    fontSize: 16,
    color: "#ff6b6b",
    cursor: "pointer",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  fab: {
    position: "fixed",
    bottom: 32,
    right: 24,
    width: 58,
    height: 58,
    borderRadius: 18,
    border: "none",
    fontSize: 28,
    color: "#fff",
    cursor: "pointer",
    boxShadow: "0 8px 32px rgba(124,111,255,0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 300,
  },
  toast: {
    position: "fixed",
    bottom: 100,
    left: "50%",
    transform: "translateX(-50%)",
    padding: "12px 24px",
    borderRadius: 14,
    color: "#fff",
    fontSize: 14,
    fontWeight: 700,
    zIndex: 999,
    whiteSpace: "nowrap",
    boxShadow: "0 4px 20px rgba(0,0,0,0.5)",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.7)",
    backdropFilter: "blur(8px)",
    zIndex: 998,
    display: "flex",
    alignItems: "flex-end",
    padding: 20,
  },
  modal: {
    background: "#13131f",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 24,
    padding: "32px 24px",
    width: "100%",
    maxWidth: 390,
    margin: "0 auto",
  },
  modalTitle: { fontSize: 20, fontWeight: 800, color: "#f0f0ff" },
  modalSub: { fontSize: 14, color: "#5a5a7a", marginTop: 8 },
  modalBtn: {
    flex: 1,
    borderRadius: 14,
    border: "none",
    padding: "14px",
    fontSize: 15,
    fontWeight: 700,
    color: "#fff",
    cursor: "pointer",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
  },
  studyBackBtn: {
    background: "rgba(255,255,255,0.1)",
    backdropFilter: "blur(8px)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 12,
    width: 38,
    height: 38,
    fontSize: 16,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  dashboardCard: {
    margin: "0 18px 20px",
    padding: 22,
    borderRadius: 24,
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(255,255,255,0.07)",
    backdropFilter: "blur(10px)",
  },
  dashboardStat: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    flex: 1,
  },
};
