export const styles = {
  root: {
    fontFamily: "'Sora', sans-serif",
    maxWidth: 430,
    margin: "0 auto",
    minHeight: "100dvh",
    background: "#0f0f0f",
    color: "#111",
    position: "relative",
    overflow: "hidden",
  },
  screen: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100dvh",
    background: "#f7f7f5",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "52px 24px 20px",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 800,
    color: "#111",
    letterSpacing: "-0.5px",
  },
  headerSub: { fontSize: 13, color: "#888", marginTop: 2 },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: "8px 20px 120px",
    overflowY: "auto",
  },
  emptyState: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: 40,
    textAlign: "center",
  },
  emptyTitle: { fontSize: 18, fontWeight: 700, color: "#333" },
  emptySub: { fontSize: 13, color: "#999" },
  topBar: {
    display: "flex",
    alignItems: "center",
    padding: "52px 20px 16px",
    gap: 12,
  },
  backBtn: {
    background: "none",
    border: "none",
    fontSize: 17,
    color: "#555",
    cursor: "pointer",
    fontWeight: 600,
    padding: "6px 0",
  },
  topTitle: { fontSize: 18, fontWeight: 700, color: "#111" },
  formWrap: {
    display: "flex",
    flexDirection: "column",
    padding: "8px 24px 40px",
    gap: 8,
  },
  label: {
    fontSize: 12,
    fontWeight: 600,
    color: "#888",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  input: {
    borderRadius: 14,
    border: "2px solid #e0e0e0",
    padding: "14px 16px",
    fontSize: 16,
    width: "100%",
  },
  textarea: {
    borderRadius: 14,
    border: "2px solid #e0e0e0",
    padding: "14px 16px",
    fontSize: 15,
    width: "100%",
    resize: "none",
  },
  colorGrid: { display: "flex", gap: 10, flexWrap: "wrap", marginTop: 4 },
  colorDot: { width: 38, height: 38, borderRadius: 12 },
  primaryBtn: {
    borderRadius: 16,
    border: "none",
    padding: "16px 24px",
    fontSize: 16,
    fontWeight: 700,
    color: "#fff",
    width: "100%",
  },
  materiaHeader: {
    display: "flex",
    alignItems: "center",
    padding: "52px 20px 20px",
    justifyContent: "space-between",
  },
  backBtnLight: {
    background: "rgba(255,255,255,0.2)",
    border: "none",
    borderRadius: 10,
    width: 36,
    height: 36,
    fontSize: 20,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitleLight: {
    fontSize: 20,
    fontWeight: 800,
    color: "#fff",
    flex: 1,
    textAlign: "center",
  },
  deleteBtnHeader: {
    background: "rgba(255,255,255,0.2)",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    width: 36,
    height: 36,
    fontSize: 16,
  },
  statsBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 24px",
  },
  stat: { display: "flex", flexDirection: "column" },
  statNum: { fontSize: 28, fontWeight: 800, lineHeight: 1 },
  statLabel: { fontSize: 12, color: "#888" },
  materiaCard: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 16,
    padding: "16px",
    cursor: "pointer",
  },
  bolillaCardBase: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 16,
    background: "#fff",
    padding: "20px 16px",
    cursor: "pointer",
    border: "1px solid #ebebeb",
    boxShadow: "0 2px 8px rgba(0,0,0,0.03)",
  },
  dot: {
    width: 38,
    height: 38,
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  itemName: { fontSize: 16, fontWeight: 700, color: "#111" },
  itemSub: { fontSize: 12, color: "#666", marginTop: 2 },
  arrow: { fontSize: 22, color: "#bbb", fontWeight: 300 },
  pill: {
    background: "#f0f0f0",
    color: "#555",
    fontSize: 12,
    fontWeight: 600,
    padding: "4px 8px",
    borderRadius: 8,
  },
  studyBtn: {
    borderRadius: 12,
    border: "none",
    padding: "12px 16px",
    fontSize: 13,
    fontWeight: 700,
    color: "#fff",
  },
  cardItemBody: {
    display: "flex",
    alignItems: "center",
    background: "#fff",
    borderRadius: 16,
    padding: "16px",
    gap: 12,
    boxShadow: "0 1px 6px rgba(0,0,0,0.06)",
    overflow: "hidden",
  },
  cardFrontText: {
    fontSize: 14,
    fontWeight: 600,
    color: "#222",
    marginBottom: 6,
    wordBreak: "break-word",
  },
  cardBackText: { fontSize: 13, color: "#666", wordBreak: "break-word" },
  deleteCardBtn: {
    background: "#FFE5E5",
    border: "none",
    borderRadius: 10,
    width: 30,
    height: 30,
    fontSize: 18,
    color: "#FF6B6B",
    cursor: "pointer",
  },
  fab: {
    position: "fixed",
    bottom: 32,
    right: 24,
    width: 60,
    height: 60,
    borderRadius: 20,
    border: "none",
    fontSize: 30,
    color: "#fff",
    cursor: "pointer",
    boxShadow: "0 8px 24px rgba(0,0,0,0.25)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  toast: {
    position: "fixed",
    bottom: 100,
    left: "50%",
    transform: "translateX(-50%)",
    padding: "12px 24px",
    borderRadius: 14,
    color: "#fff",
    fontSize: 14,
    fontWeight: 700,
    zIndex: 999,
    whiteSpace: "nowrap",
    boxShadow: "0 4px 20px rgba(0,0,0,0.3)",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.5)",
    zIndex: 998,
    display: "flex",
    alignItems: "flex-end",
    padding: 20,
  },
  modal: {
    background: "#1a1a1a",
    borderRadius: 24,
    padding: "32px 24px",
    width: "100%",
    maxWidth: 390,
    margin: "0 auto",
  },
  modalTitle: { fontSize: 20, fontWeight: 800, color: "#fff" },
  modalSub: { fontSize: 14, color: "#888", marginTop: 8 },
  modalBtn: {
    flex: 1,
    borderRadius: 14,
    border: "none",
    padding: "14px",
    fontSize: 15,
    fontWeight: 700,
    color: "#fff",
  },
  studyBackBtn: {
    background: "rgba(255,255,255,0.2)",
    border: "none",
    borderRadius: 12,
    width: 36,
    height: 36,
    fontSize: 18,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  dashboardCard: {
    background: "#fff",
    margin: "0 20px 24px",
    padding: 24,
    borderRadius: 24,
    boxShadow: "0 8px 24px rgba(0,0,0,0.05)",
  },
  dashboardStat: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    flex: 1,
  },
};
